name: Publish Development Build
on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the KatanaDupe
      - uses: actions/checkout@v2
      
      - name: Set up Java 21
      - uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: adopt
          
      - name: Set up build environment
        run: chmod +x gradlew*

      - name: Build
        run: ./gradlew build
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: latest
          prerelease: false
          title: Dev Build
          files: |
            ./build/libs/*.jar
