name: Publish Development Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the KatanaDupe
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up build environment
        run: chmod +x gradlew

      - name: Build the Project
        run: ./gradlew build

      - name: Release the Project
        uses: softprops/action-gh-release@v2
