name: Publish Development Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the KatanaDupe
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Create tag
        run: |
         git tag v1.0.${{ github.run_number }}
         git push origin v1.0.${{ github.run_number }}
         
      - name: Set up build environment
        run: chmod +x gradlew

      - name: Build the Project
        run: ./gradlew build

      - name: Release the Project
        uses: softprops/action-gh-release@v2
